[package]
name = "bsky_tui"
version = "0.0.1"
edition = "2018"

[dependencies]
crossterm = "0.27"
eyre = "0.6"
seahorse = "2.1"
tokio = { version = "1", features = ["full"] }
ratatui = { version = "0.22", features = ["all-widgets"] }
atrium-api = "0.4"
atrium-xrpc = "0.3"
chrono = "0.4"
